server:
  port: 8080

spring:
  datasource:
      url:
        jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRet
      username: root
      password: Tmt@123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name:
      arch-mybatis

mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    # 下划线自动转驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.perry.archmybatis: debug

