server:
  port: 8080

spring:
  application:
    name: arch-swagger
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Tmt@123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


#springfox:
#  documentation:
#    # 是否启用Swagger扫描代码生成文档
#    enabled: true
#    open-api:
#      # 是否启用Swagger的open-api
#      enabled: false
#    swagger-ui:
#      # 是否启用Swagger的Web UI
#      enabled: true
#      # 配置文档基础路径，此时路径为：/doc/swagger-ui/index.html
#      base-url: /doc